---
language: ruby
sudo: false
before_install: gem install bundler -v 2.0.1
bundler_args: --without tools
script: "bundle exec rake ci"
rvm:
  - 2.4.6
  - 2.5.5
  - ruby-head
  - jruby-9.1.5.0
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
branches:
  only: master
notifications:
  email: false
